### ISSUE TITLE
useRuntimeConfig is not defined

### ISSUE THREAD

**Issue by lollobene** [rrd108/nuxt-api-shield#9]
Hey, I'm facing this error:

[nuxt] [request error] [unhandled] [500] useRuntimeConfig is not defined
  at isBanExpired (./node_modules/nuxt-api-shield/dist/runtime/server/utils/isBanExpired.mjs:2:19)  
  at Object.handler (./node_modules/nuxt-api-shield/dist/runtime/server/middleware/shield.mjs:24:7)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ./node_modules/h3/dist/index.mjs:1962:19  
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2249:7)
  
 Do you know how to fix this?

**Comment by rrd108** [comment]
Can you provide a reproduction link?

**Comment by rrd108** [comment]
Connected to https://github.com/nuxt/nuxt/issues/24841 I guess
